[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/kanagawa-paper-ink.toml"]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Command"

[window]
startup_mode = "Maximized"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window.padding]
x = 2
y = 2
